### PR TITLE
Lcl list fix

### PR DESCRIPTION
**Pull request by timitoc**
Fixed mistake here: public LCLList<OBJECT> remove(OBJECT object) (Item wasn't removed from
the m_Erasables LCLString).
Made clean method run better.

Disclaimer: I might even have syntax error since I haven't configured the project yet.

### CODE REVIEW

**Comment by SasLuca** [comment]
Thanks for the fix in LCLList#remove(OBJECT object), however the way you made the LCLList#clean() method is not more efficient since you are creating a new Array and LCLString and populate them with the objects that are not marked for erase. Creating new objects is the very expensive, and also it's not memory efficient, it's way more efficient to just remove the elements that are marked for erasure from the existing Array and LCLString objects. Creating an LCLString is even more useles since it's basically just a mutable string and it's used specifically for use when you want to alter the contents of the string very often.

P.S. : Thanks for bug you mention, please make an issue and I will fix it in the next commit. Also, you can not make a variable private/public/protected inside a method.

**Comment by timitoc** [comment]
Sorry for making the variable private, it was blind coding :P
In the clean method is better to implement the removal of multiple elements the way I have done it. That's because adding an elements to the end takes constant time, whereas the removal of an element takes linear time, trust me. Since I create a new object it is just barely memory inefficient but only by a constant. But the fact that 1 erasure makes up for N insertions makes it worthed. 
 

    On Friday, September 9, 2016 4:26 PM, SasLuca <notifications@github.com> wrote:
 

 Closed #3.—

**Comment by SasLuca** [comment]
Im investigating it, creating a new LCLString though does not make sense since LCLString is basically a mutable string.

**Comment by timitoc** [comment]
You might want to create it from a string of '0'-s but again **do not** mutate the old one by removing those elements. 
If you don't trust me just compare my implementation against yours with a test. Erase 1.000.000 elements and then clean. Mine should be done in a second at most. With your implementation it might take hours..

**Comment by SasLuca** [comment]
Ok, I tested it and made the necessary modifications. Im testing whether I should use a normal string or an LCLString now. Please make this an issue and I will make a commit with the fix. BTW, the prefix m_ is only used on private members of an object, no need to use it inside a method :) 
Thanks a lot for the help. I will also update the clear methods in LCL as well.

**Comment by SasLuca** [comment]
Also, I need to test this on Android as well. The Android documentation notes that on Android creating objects is pretty expensive. Eventually we could have different implementations regarding the platform.

https://developer.android.com/training/articles/perf-tips.html

**Comment by timitoc** [comment]
Even if it's android my implementation will be way better if you erase more than 2 elements or so.

**Comment by SasLuca** [comment]
Ok, thanks for the help. I tested it and you'r right, however on LCLString is faster to use LCLString#clear than to create a new one. If you want to do more tests use LCLTimePoints to measure time like so:

`LCLTimePoints.addTimePoint(0);
//your code 
long timeItTookToExecuteCode = LCLTimePoints.getInNanoSeconds(0);`

**Pull request merged**
